version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rork_postgres
    environment:
      POSTGRES_DB: rork_marketplace
      POSTGRES_USER: rork_user
      POSTGRES_PASSWORD: rork_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rork_user -d rork_marketplace"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
