[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["echo 'Skipping root install - using custom build command'"]
cacheDirectories = []

[phases.build]
cmds = ["cd backend && npm ci && npm run build"]

[start]
cmd = "cd backend && npm run prod:start"
