[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run prod:start"

[variables]
NODE_ENV = "production"

# Exclude frontend files from build context
[phases.setup.files]
include = [
  "src/**/*",
  "package.json",
  "package-lock.json",
  "tsconfig.json",
  "drizzle.config.ts",
  ".env*"
]
exclude = [
  "app/**/*",
  "components/**/*",
  "assets/**/*",
  "*.tsx",
  "*.ts"
]
